name: monster-ui-application-pbxs
custom_files: null
exposure: private
base_branch: origin/5.5
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  rockylinux9:
    name: monster-ui-application-pbxs
    app_name: pbxs
    license: 'MPL 2.0'
    group: Productivity/Telephony
    url: 'http://www.2600hz.org/'
    vendor: 2600Hz
    dist: .el9
metapackage:
  -
    name: meta-monster-ui
    branch: '5.5'
    package: monster-ui-application-pbxs
    type: required
dependencies: null
